# spring configuration
spring:
   application:
      name: emaillist
   profiles:
      active: development
      
      
---
# common spring boot configuration
spring:
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/assets/
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html

server:
   error:
      whitelabel:
         enabled: false
      path: /error
   servlet:
      context-path: /
      encoding:
         charset: utf-8
         enabled: true


---
# development profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   devtools:
      livereload:
         enabled: true
   thymeleaf:
      cache: false
         
server:
   port: 8080

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: DEBUG

eureka:
   client:
      fetchRegistry: true
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://localhost:8761/eureka         


---
# production profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   thymeleaf:
      cache: true

server:
   port: 8093

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            emaillist:
               exception: ERROR
         
eureka:
   client:
      fetchRegistry: true
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://192.168.66.4:8761/eureka